### PR TITLE
chore(CI): add node v10 to CI

### PR DESCRIPTION
**Pull request by nfischer**
This adds Node v10 to Appveyor and Travis CI.

### CODE REVIEW

**Comment by nfischer** [comment]
Appveyor failures are due to #132, this PR is OK.

**Comment by nfischer** [comment]
Rebased off master, so I don't expect any CI failures.

**Comment by nfischer** [comment]
I think it's OK to land this before https://github.com/shelljs/shelljs/pull/856. I don't think that reflects a significant node-v10-incompatibility in shelljs.

**Comment by freitagbr** [comment]
LGTM

**Pull request merged**
