### PR TITLE
test: improve test coverage

### PR DESCRIPTION
**Pull request by nfischer**
Played around with the test framework a bit more, and got some better test coverage. Let me know if anything should be revised.

Not sure if we can get much more coverage without modifying the src, since I think we have some branches that were only reachable via old versions of ShellJS.

### CODE REVIEW

**Comment by levithomason** [comment]
Could we move the mocks to `test/mocks` since they'll be needed in all tests?  Once tests pass, this is looking much better.

**Comment by nfischer** [comment]
Whoops, forgot about the lint warning. That's been fixed (so tests should now pass).

I moved mocks into `test/mocks.js`

**Comment by levithomason** [comment]
Sorry, should have been more clear on the mocks.  I mean one file per mock.  It is also helpful to have mocks mimic the exact shape of the originals.  This way the instances can be swapped in and out easily and existing code can use it unawares.

I'm thinking for console/process mocks specifically it would also be helpful to:
- allow direct use without mocking the global
- allow inline mock/restore of the originals

How about something like this for the console mock?

```js
// test/mocks/console.js
import { processMock } from './process'

const noop = () => undefined

export const consoleMock = {
  // utils
  original: { ...global.console },
  mock() {
    Object.assign(global.console, this)
  },
  restore() {
    Object.assign(global.console, this.original)
  },

  // console methods
  assert: noop,
  dir: noop,
  error(...msgs) {
    processMock.stderr += `${msgs.join(' ')}\n`;
  },
  info(...args) {
    this.log(...args)
  },
  log(...msgs) {
    processMock.stdout += `${msgs.join(' ')}\n`;
  },
  time: noop,
  timeEnd: noop,
  trace: noop,
  warn(...args) {
    this.error(...args)
  },
}
```

Direct usage:

```js
import { consoleMock } from '../mocks/console'

consoleMock.log('hi') // logs to processMock.stdout
```

Mock/restore the global:

```js
import { consoleMock } from '../mocks/console'

consoleMock.mock()
console.log('hi again')   // logs to processMock.stdout

console.restore()
console.log("it's back!") // logs to process.stdout
```

Then similar for the process mock.  Also, we can do this in another PR if helpful.

**Comment by nfischer** [comment]
Sure, I'll refactor it sometime tonight

**Comment by nfischer** [comment]
@levithomason Actually, probably won't have time to do the refactor. I tried a couple things out last night, but the `reset()` never worked quite right.

Is there a big drawback to the way it's implemented currently? It's perhaps a little messy, but it's just a test framework. Personally, I'd rather get the test coverage than do the refactor, but I don't mind waiting if someone else wants to take it up.

**Comment by levithomason** [comment]
LGTM, for this PR since it's about adding coverage.  I'll scaffold the mocks in another.

**Comment by nfischer** [comment]
:+1: Sounds good to me

**Pull request merged**
