### PR TITLE
fix(echo): fix #5

### LINKED ISSUE #5: echo outputs twice
```bash
$ shx echo hello world
hello world
hello world
```

I think the simplest fix is to check for if we get `echo` as a function, and not output its return value (since `echo` already outputs things).

### PR DESCRIPTION
**Pull request by nfischer**
Fixes #5

### CODE REVIEW

**Comment by levithomason** [comment]
Cool, I had done the same in the [ShellJS PR](https://github.com/shelljs/shelljs/pull/386/files#diff-20fa2da323c6f14c28f42688efa0e494R30).  LGTM!

**Comment by nfischer** [comment]
@levithomason I'm going to wait on the build system getting fixed (I can't actually run anything as-is). Once that's fixed, I can test manually and merge.

**Comment by levithomason** [comment]
If you want to rebase and merge this guy, I'll then do the same on the ES6 PRs.  This should minimize the conflicts you have to deal with.

**Comment by nfischer** [comment]
This should be good now. Merging.

**Pull request merged**
