### PR TITLE
Lowering test coverage in order to test README badge

### PR DESCRIPTION
**Pull request by nfischer**
**Do not merge**

This is just a test to verify #51 is actually ok.

### CODE REVIEW

**Comment by levithomason** [comment]
You're correct, the badge is reporting the 42% even though it is pointed to master.  Hm.

**Comment by levithomason** [comment]
Looks like it is an issue with codecov itself?  This PR shows 42% right now, but clicking branches > master (https://codecov.io/gh/shelljs/shx/branch/master) also shows 42%.

**Comment by nfischer** [comment]
Hmmm... that definitely seems strange. But yeah, I can't seem to find a way to point at the real branch of master on Github.

This may be due to how code coverage is set up. Perhaps it's because it gets triggered during CI, which is after it merges into `master` on the CI machine (but not on the remote repo)?

This isn't the biggest deal. I just thought I'd point it out since it could be misleading if we're unaware.

**Comment by levithomason** [comment]
Agree on all counts.  I spent some time in their interface trying to see how to separate the tested PR merge commit from the actual master commit to no avail.

Codecov is still pretty new and has a few issues.  We use it at work and have run into a few other reported coverage level problems.

If you'd like to dig on this more, we could investigate use of a codecov.yml and see if one of the settings there resolves this.  Otherwise, feel free to close these out for now.

**Comment by nfischer** [comment]
This appears to be an issue for others, as seen in codecov/support#191. Closing this PR, since we obviously wouldn't want to merge it and the issue appears to be out of our hands.

**Comment by levithomason** [comment]
Want to kill the branch as well I assume?

**Comment by nfischer** [comment]
Just to document the results we saw, coverage went down from 84% to 42% by removing test cases. This was visible in the README badge, despite the fact that we hadn't merged this PR. I'm including a screenshot of badge (in the comments of this PR) just in case the badge updates as master branch changes:

screenshot from 2016-05-10 16-33-01

**Comment by ariporad** [comment]
Hmm... I don't really like this.
What are your thoughts on considering coveralls? They've worked pretty well for me in the past, and I know that they do support this.


On Tue, May 10, 2016 at 4:35 PM, Nate Fischer <notifications@github.com> wrote:
Just to document the results we saw, coverage went down from 84% to 42% by removing test cases. This was visible in the README badge, despite the fact that we hadn't merged this PR. I'm including a screenshot of badge (in the comments of this PR) just in case the badge updates as master branch changes:

[https://cloud.githubusercontent.com/assets/5801521/15165738/0cefbf46-16cd-11e6-91e3-48d992858c06.png]

**Comment by levithomason** [comment]
i'd like to give them a little while and see how it goes. if they are responsive and quick on fixes, I say stay.  otherwise, a switch is needed.  Thoughts?

**Comment by ariporad** [comment]
SGTM

**Pull request closed without merging**
