### PR TITLE
chore(changelog): create and add script

### LINKED ISSUE #18: Setup changelog

### PR DESCRIPTION
**Pull request by levithomason**
Resolves #18.

The changelog and changelog commit in this PR were generated using the script.  See commit:
```
docs(changelog): updated by levithomason [ci skip]
```

## Generate / Update

```shell
› npm run changelog 

...generating changelog (be patient)
...committing updated changelog
Done.  You can now 'git push' the updated changelog.
```

## No Changes

When the the changelog is already up to date and the script is run:

```shell
› npm run changelog

...generating changelog (be patient)
CHANGELOG.md already up-to-date.
```

## Future PRs

Later, this script can be integrated into the CI process.  The repo/branch/user can be inferred from CI env vars at that time as well.   This just gets it started.

### CODE REVIEW

**Comment by nfischer** [comment]
> Later, this script can be integrated into the CI process.

SGTM. I like the idea of doing it manually for the time being. When the manual way gets to be too much of a pain, we can automate it.

Just tried this out, and it seems pretty good. The only thing I don't like is that it tries to automatically push the commit, which I wouldn't expect. I'm fine with auto-generating the commit though. If @ariporad disagrees, I'm fine with going with majority opinion on this though.

Also, I think we should try to keep PR titles to the commit format @ariporad suggested, since that's what the final commit message gets based off of after the squash-merge (correct me if I'm mistaken). That's only if we're going to continue with that format for commit messages.

**Comment by levithomason** [comment]
I'm down with manual process, automating only if necessary.  Also good with no automatic push, I will remove it.  

The squash message is editable at merge time.  Clicking the merge button switches it to an "edit message" input.

**Comment by levithomason** [comment]
Done.  Also, just realized the PR titles _will_ become part of the changelog as well!  Updating...

**Comment by nfischer** [comment]
^ good to know. I feel like github's changing everyday, it's sometimes hard to keep up with it all

**Comment by levithomason** [comment]
One other thought, this could be done on post release:*.  That way the release always includes the latest changelog.  If we did that, I'd feel like an auto commit / push would be OK.

In other words, the release workflow would now include an updated changelog at the end.  Thoughts?

**Comment by nfischer** [comment]
LGTM

**Comment by levithomason** [comment]
Codecov is gagging on this PR for some reason, can't rerun.  Going to merge since it touches no functional code.

**Pull request merged**
