### PR TITLE
chore: switch to shelljs-changelog

### PR DESCRIPTION
**Pull request by nfischer**
Same script, but now it's refactored out as a dependency, and it runs in Node instead of bash.

### CODE REVIEW

**Comment by levithomason** [comment]
I'd think keeping the cli namespaced `shelljs-changelog` or `shx-changelog` would be a good idea.  This PR however LGTM!

**Comment by nfischer** [comment]
SGTM. I'll update that for the next version of the changelog and release scripts

**Comment by nfischer** [comment]
This is bumped to the most recent version of shelljs-changelog, with the namespaced CLI.

**Comment by ariporad** [comment]
LGTM, but could you fix the merge errors? Thx

**Pull request merged**
